#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Timmins")]
public partial class appointmentsDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Inserttbl_appointment(tbl_appointment instance);
  partial void Updatetbl_appointment(tbl_appointment instance);
  partial void Deletetbl_appointment(tbl_appointment instance);
  #endregion
	
	public appointmentsDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TimminsConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public appointmentsDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public appointmentsDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public appointmentsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public appointmentsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tbl_appointment> tbl_appointments
	{
		get
		{
			return this.GetTable<tbl_appointment>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="timmins.tbl_appointment")]
public partial class tbl_appointment : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _appointment_id;
	
	private string _appointment_name;
	
	private string _appointment_email;
	
	private System.Nullable<System.DateTime> _appointment_date;
	
	private string _appointment_time;
	
	private string _appointment_confirmation;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onappointment_idChanging(int value);
    partial void Onappointment_idChanged();
    partial void Onappointment_nameChanging(string value);
    partial void Onappointment_nameChanged();
    partial void Onappointment_emailChanging(string value);
    partial void Onappointment_emailChanged();
    partial void Onappointment_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onappointment_dateChanged();
    partial void Onappointment_timeChanging(string value);
    partial void Onappointment_timeChanged();
    partial void Onappointment_confirmationChanging(string value);
    partial void Onappointment_confirmationChanged();
    #endregion
	
	public tbl_appointment()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_appointment_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int appointment_id
	{
		get
		{
			return this._appointment_id;
		}
		set
		{
			if ((this._appointment_id != value))
			{
				this.Onappointment_idChanging(value);
				this.SendPropertyChanging();
				this._appointment_id = value;
				this.SendPropertyChanged("appointment_id");
				this.Onappointment_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_appointment_name", DbType="VarChar(50)")]
	public string appointment_name
	{
		get
		{
			return this._appointment_name;
		}
		set
		{
			if ((this._appointment_name != value))
			{
				this.Onappointment_nameChanging(value);
				this.SendPropertyChanging();
				this._appointment_name = value;
				this.SendPropertyChanged("appointment_name");
				this.Onappointment_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_appointment_email", DbType="VarChar(50)")]
	public string appointment_email
	{
		get
		{
			return this._appointment_email;
		}
		set
		{
			if ((this._appointment_email != value))
			{
				this.Onappointment_emailChanging(value);
				this.SendPropertyChanging();
				this._appointment_email = value;
				this.SendPropertyChanged("appointment_email");
				this.Onappointment_emailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_appointment_date", DbType="Date")]
	public System.Nullable<System.DateTime> appointment_date
	{
		get
		{
			return this._appointment_date;
		}
		set
		{
			if ((this._appointment_date != value))
			{
				this.Onappointment_dateChanging(value);
				this.SendPropertyChanging();
				this._appointment_date = value;
				this.SendPropertyChanged("appointment_date");
				this.Onappointment_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_appointment_time", DbType="VarChar(50)")]
	public string appointment_time
	{
		get
		{
			return this._appointment_time;
		}
		set
		{
			if ((this._appointment_time != value))
			{
				this.Onappointment_timeChanging(value);
				this.SendPropertyChanging();
				this._appointment_time = value;
				this.SendPropertyChanged("appointment_time");
				this.Onappointment_timeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_appointment_confirmation", DbType="VarChar(50)")]
	public string appointment_confirmation
	{
		get
		{
			return this._appointment_confirmation;
		}
		set
		{
			if ((this._appointment_confirmation != value))
			{
				this.Onappointment_confirmationChanging(value);
				this.SendPropertyChanging();
				this._appointment_confirmation = value;
				this.SendPropertyChanged("appointment_confirmation");
				this.Onappointment_confirmationChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
