#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="timmins")]
public partial class articlesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Inserttbl_article(tbl_article instance);
  partial void Updatetbl_article(tbl_article instance);
  partial void Deletetbl_article(tbl_article instance);
  #endregion
	
	public articlesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["timminsConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public articlesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public articlesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public articlesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public articlesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tbl_article> tbl_articles
	{
		get
		{
			return this.GetTable<tbl_article>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="timmins.tbl_article")]
public partial class tbl_article : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _heading;
	
	private string _intro;
	
	private string _paragraph;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnheadingChanging(string value);
    partial void OnheadingChanged();
    partial void OnintroChanging(string value);
    partial void OnintroChanged();
    partial void OnparagraphChanging(string value);
    partial void OnparagraphChanged();
    #endregion
	
	public tbl_article()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_heading", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string heading
	{
		get
		{
			return this._heading;
		}
		set
		{
			if ((this._heading != value))
			{
				this.OnheadingChanging(value);
				this.SendPropertyChanging();
				this._heading = value;
				this.SendPropertyChanged("heading");
				this.OnheadingChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intro", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string intro
	{
		get
		{
			return this._intro;
		}
		set
		{
			if ((this._intro != value))
			{
				this.OnintroChanging(value);
				this.SendPropertyChanging();
				this._intro = value;
				this.SendPropertyChanged("intro");
				this.OnintroChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paragraph", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string paragraph
	{
		get
		{
			return this._paragraph;
		}
		set
		{
			if ((this._paragraph != value))
			{
				this.OnparagraphChanging(value);
				this.SendPropertyChanging();
				this._paragraph = value;
				this.SendPropertyChanged("paragraph");
				this.OnparagraphChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
