<?xml version="1.0" encoding="utf-8"?><Database Name="Timmins" Class="galleryDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=snare.arvixe.com;Initial Catalog=Timmins;Persist Security Info=True;User ID=timmins" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="TimminsConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="timmins.Gallery" Member="Galleries">
    <Type Name="Gallery">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MainImage" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ThumbNail" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>