#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Timmins")]
public partial class pollDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertpoll_answer(poll_answer instance);
  partial void Updatepoll_answer(poll_answer instance);
  partial void Deletepoll_answer(poll_answer instance);
  partial void Insertpoll_choice(poll_choice instance);
  partial void Updatepoll_choice(poll_choice instance);
  partial void Deletepoll_choice(poll_choice instance);
  partial void Insertpoll_question(poll_question instance);
  partial void Updatepoll_question(poll_question instance);
  partial void Deletepoll_question(poll_question instance);
  #endregion
	
	public pollDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TimminsConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public pollDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public pollDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public pollDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public pollDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<poll_answer> poll_answers
	{
		get
		{
			return this.GetTable<poll_answer>();
		}
	}
	
	public System.Data.Linq.Table<poll_choice> poll_choices
	{
		get
		{
			return this.GetTable<poll_choice>();
		}
	}
	
	public System.Data.Linq.Table<poll_question> poll_questions
	{
		get
		{
			return this.GetTable<poll_question>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="timmins.poll_answer")]
public partial class poll_answer : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _answer_id;
	
	private string _answer;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onanswer_idChanging(int value);
    partial void Onanswer_idChanged();
    partial void OnanswerChanging(string value);
    partial void OnanswerChanged();
    #endregion
	
	public poll_answer()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_answer_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int answer_id
	{
		get
		{
			return this._answer_id;
		}
		set
		{
			if ((this._answer_id != value))
			{
				this.Onanswer_idChanging(value);
				this.SendPropertyChanging();
				this._answer_id = value;
				this.SendPropertyChanged("answer_id");
				this.Onanswer_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_answer", DbType="VarChar(MAX)")]
	public string answer
	{
		get
		{
			return this._answer;
		}
		set
		{
			if ((this._answer != value))
			{
				this.OnanswerChanging(value);
				this.SendPropertyChanging();
				this._answer = value;
				this.SendPropertyChanged("answer");
				this.OnanswerChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="timmins.poll_choice")]
public partial class poll_choice : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IDpc;
	
	private string _option;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDpcChanging(int value);
    partial void OnIDpcChanged();
    partial void OnoptionChanging(string value);
    partial void OnoptionChanged();
    #endregion
	
	public poll_choice()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDpc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IDpc
	{
		get
		{
			return this._IDpc;
		}
		set
		{
			if ((this._IDpc != value))
			{
				this.OnIDpcChanging(value);
				this.SendPropertyChanging();
				this._IDpc = value;
				this.SendPropertyChanged("IDpc");
				this.OnIDpcChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[option]", Storage="_option", DbType="NVarChar(50)")]
	public string option
	{
		get
		{
			return this._option;
		}
		set
		{
			if ((this._option != value))
			{
				this.OnoptionChanging(value);
				this.SendPropertyChanging();
				this._option = value;
				this.SendPropertyChanged("option");
				this.OnoptionChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="timmins.poll_question")]
public partial class poll_question : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IDq;
	
	private string _question;
	
	private System.Nullable<bool> _live;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDqChanging(int value);
    partial void OnIDqChanged();
    partial void OnquestionChanging(string value);
    partial void OnquestionChanged();
    partial void OnliveChanging(System.Nullable<bool> value);
    partial void OnliveChanged();
    #endregion
	
	public poll_question()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDq", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IDq
	{
		get
		{
			return this._IDq;
		}
		set
		{
			if ((this._IDq != value))
			{
				this.OnIDqChanging(value);
				this.SendPropertyChanging();
				this._IDq = value;
				this.SendPropertyChanged("IDq");
				this.OnIDqChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_question", DbType="NVarChar(MAX)")]
	public string question
	{
		get
		{
			return this._question;
		}
		set
		{
			if ((this._question != value))
			{
				this.OnquestionChanging(value);
				this.SendPropertyChanging();
				this._question = value;
				this.SendPropertyChanged("question");
				this.OnquestionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_live", DbType="Bit")]
	public System.Nullable<bool> live
	{
		get
		{
			return this._live;
		}
		set
		{
			if ((this._live != value))
			{
				this.OnliveChanging(value);
				this.SendPropertyChanging();
				this._live = value;
				this.SendPropertyChanged("live");
				this.OnliveChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
