#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="timmins")]
public partial class specialties_doctorsDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Inserttbl_doctor(tbl_doctor instance);
  partial void Updatetbl_doctor(tbl_doctor instance);
  partial void Deletetbl_doctor(tbl_doctor instance);
  partial void Inserttbl_specialty(tbl_specialty instance);
  partial void Updatetbl_specialty(tbl_specialty instance);
  partial void Deletetbl_specialty(tbl_specialty instance);
  #endregion
	
	public specialties_doctorsDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["timminsConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public specialties_doctorsDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public specialties_doctorsDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public specialties_doctorsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public specialties_doctorsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tbl_doctor> tbl_doctors
	{
		get
		{
			return this.GetTable<tbl_doctor>();
		}
	}
	
	public System.Data.Linq.Table<tbl_specialty> tbl_specialties
	{
		get
		{
			return this.GetTable<tbl_specialty>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="timmins.tbl_doctors")]
public partial class tbl_doctor : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _doctor_id;
	
	private string _first_name;
	
	private string _last_name;
	
	private string _gender;
	
	private string _email;
	
	private string _bio;
	
	private int _specialty_id;
	
	private EntityRef<tbl_specialty> _tbl_specialty;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondoctor_idChanging(int value);
    partial void Ondoctor_idChanged();
    partial void Onfirst_nameChanging(string value);
    partial void Onfirst_nameChanged();
    partial void Onlast_nameChanging(string value);
    partial void Onlast_nameChanged();
    partial void OngenderChanging(string value);
    partial void OngenderChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnbioChanging(string value);
    partial void OnbioChanged();
    partial void Onspecialty_idChanging(int value);
    partial void Onspecialty_idChanged();
    #endregion
	
	public tbl_doctor()
	{
		this._tbl_specialty = default(EntityRef<tbl_specialty>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doctor_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int doctor_id
	{
		get
		{
			return this._doctor_id;
		}
		set
		{
			if ((this._doctor_id != value))
			{
				if (this._tbl_specialty.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Ondoctor_idChanging(value);
				this.SendPropertyChanging();
				this._doctor_id = value;
				this.SendPropertyChanged("doctor_id");
				this.Ondoctor_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_first_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string first_name
	{
		get
		{
			return this._first_name;
		}
		set
		{
			if ((this._first_name != value))
			{
				this.Onfirst_nameChanging(value);
				this.SendPropertyChanging();
				this._first_name = value;
				this.SendPropertyChanged("first_name");
				this.Onfirst_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string last_name
	{
		get
		{
			return this._last_name;
		}
		set
		{
			if ((this._last_name != value))
			{
				this.Onlast_nameChanging(value);
				this.SendPropertyChanging();
				this._last_name = value;
				this.SendPropertyChanged("last_name");
				this.Onlast_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
	public string gender
	{
		get
		{
			return this._gender;
		}
		set
		{
			if ((this._gender != value))
			{
				this.OngenderChanging(value);
				this.SendPropertyChanging();
				this._gender = value;
				this.SendPropertyChanged("gender");
				this.OngenderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bio", DbType="VarChar(MAX)")]
	public string bio
	{
		get
		{
			return this._bio;
		}
		set
		{
			if ((this._bio != value))
			{
				this.OnbioChanging(value);
				this.SendPropertyChanging();
				this._bio = value;
				this.SendPropertyChanged("bio");
				this.OnbioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_specialty_id", DbType="Int NOT NULL")]
	public int specialty_id
	{
		get
		{
			return this._specialty_id;
		}
		set
		{
			if ((this._specialty_id != value))
			{
				this.Onspecialty_idChanging(value);
				this.SendPropertyChanging();
				this._specialty_id = value;
				this.SendPropertyChanged("specialty_id");
				this.Onspecialty_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_specialty_tbl_doctor", Storage="_tbl_specialty", ThisKey="doctor_id", OtherKey="specialty_id", IsForeignKey=true)]
	public tbl_specialty tbl_specialty
	{
		get
		{
			return this._tbl_specialty.Entity;
		}
		set
		{
			tbl_specialty previousValue = this._tbl_specialty.Entity;
			if (((previousValue != value) 
						|| (this._tbl_specialty.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tbl_specialty.Entity = null;
					previousValue.tbl_doctor = null;
				}
				this._tbl_specialty.Entity = value;
				if ((value != null))
				{
					value.tbl_doctor = this;
					this._doctor_id = value.specialty_id;
				}
				else
				{
					this._doctor_id = default(int);
				}
				this.SendPropertyChanged("tbl_specialty");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="timmins.tbl_specialties")]
public partial class tbl_specialty : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _specialty_id;
	
	private string _specialty;
	
	private EntityRef<tbl_doctor> _tbl_doctor;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onspecialty_idChanging(int value);
    partial void Onspecialty_idChanged();
    partial void OnspecialtyChanging(string value);
    partial void OnspecialtyChanged();
    #endregion
	
	public tbl_specialty()
	{
		this._tbl_doctor = default(EntityRef<tbl_doctor>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_specialty_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int specialty_id
	{
		get
		{
			return this._specialty_id;
		}
		set
		{
			if ((this._specialty_id != value))
			{
				this.Onspecialty_idChanging(value);
				this.SendPropertyChanging();
				this._specialty_id = value;
				this.SendPropertyChanged("specialty_id");
				this.Onspecialty_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_specialty", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string specialty
	{
		get
		{
			return this._specialty;
		}
		set
		{
			if ((this._specialty != value))
			{
				this.OnspecialtyChanging(value);
				this.SendPropertyChanging();
				this._specialty = value;
				this.SendPropertyChanged("specialty");
				this.OnspecialtyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_specialty_tbl_doctor", Storage="_tbl_doctor", ThisKey="specialty_id", OtherKey="doctor_id", IsUnique=true, IsForeignKey=false)]
	public tbl_doctor tbl_doctor
	{
		get
		{
			return this._tbl_doctor.Entity;
		}
		set
		{
			tbl_doctor previousValue = this._tbl_doctor.Entity;
			if (((previousValue != value) 
						|| (this._tbl_doctor.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tbl_doctor.Entity = null;
					previousValue.tbl_specialty = null;
				}
				this._tbl_doctor.Entity = value;
				if ((value != null))
				{
					value.tbl_specialty = this;
				}
				this.SendPropertyChanged("tbl_doctor");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
